import type { Finding, ScanResult } from "./types";
import { CATEGORY_META } from "./types";
import { scoreLabel, severityCount } from "./score";

interface ManualItem {
  id: string;
  text: string;
  done: boolean;
}

export function clientSummaryText(scan: ScanResult): string {
  const high = severityCount(scan.findings, "high");
  const med  = severityCount(scan.findings, "med");
  const { label } = scoreLabel(scan.score);
  if (high === 0 && med <= 2) {
    return `The site is in great shape and effectively ready for launch (score: ${scan.score}/100). We've flagged a small number of polish items the team will address before handoff.`;
  }
  if (high === 0) {
    return `The site is on track for launch (score: ${scan.score}/100). We've identified a handful of refinements — primarily mobile polish and copy details — that the team will resolve in the final pass.`;
  }
  return `The site is taking shape (score: ${scan.score}/100 — ${label.toLowerCase()}). We've identified ${high} item${high === 1 ? "" : "s"} that should be resolved before going live, plus ${med} medium-priority refinements. The team is actively working through these and will share an updated build shortly.`;
}

export function buildMarkdownReport(
  scan: ScanResult,
  manualItems: ManualItem[],
  projectName: string,
): string {
  const { url, scannedAt, findings, score } = scan;
  const { label } = scoreLabel(score);
  const high = findings.filter(f => f.sev === "high");
  const med  = findings.filter(f => f.sev === "med");
  const low  = findings.filter(f => f.sev === "low");

  const renderFindings = (list: Finding[]) =>
    list.map(f =>
      `- **[${CATEGORY_META[f.category].label}]** ${f.title}\n  - ${f.detail}\n  - _Fix:_ ${f.fix}${f.source ? `\n  - _Source:_ ${f.source}` : ""}`
    ).join("\n");

  const prio = [...high, ...med, ...low];

  const lines: string[] = [
    `# Launch QA Report`,
    ``,
    projectName ? `**Project:** ${projectName}  ` : "",
    `**URL:** ${url}  `,
    `**Scanned:** ${new Date(scannedAt).toLocaleString()}  `,
    `**Launch Readiness Score:** ${score} / 100 — ${label}`,
    ``,
    scan.lighthouse ? lighthouseSection(scan) : "",
    `## Executive summary`,
    ``,
    `The build was scanned across SEO, accessibility, links, mobile, copy/brand, and performance. ${high.length} high-severity, ${med.length} medium-severity, and ${low.length} low-severity findings were identified. ${high.length === 0 ? "No launch blockers detected." : `${high.length} item${high.length === 1 ? "" : "s"} should be resolved before go-live.`}`,
    ``,
    `## High severity (${high.length})`,
    high.length ? renderFindings(high) : "_None_",
    ``,
    `## Medium severity (${med.length})`,
    med.length ? renderFindings(med) : "_None_",
    ``,
    `## Low severity (${low.length})`,
    low.length ? renderFindings(low) : "_None_",
    ``,
    `## Recommended fixes (priority order)`,
    ``,
    prio.slice(0, 10).map((f, i) => `${i + 1}. ${f.title} — ${f.fix}`).join("\n"),
    ``,
    `## Client-friendly summary`,
    ``,
    clientSummaryText(scan),
    ``,
    `## Developer checklist`,
    ``,
    prio.map(f => `- [ ] [${f.sev.toUpperCase()}] ${f.title}`).join("\n"),
    ``,
    manualItems.length ? `## Manual QA items\n\n${manualItems.map(i => `- [${i.done ? "x" : " "}] ${i.text}`).join("\n")}` : "",
    ``,
    `---`,
    `_Generated by Launch QA Assistant_`,
  ];
  return lines.filter(Boolean).join("\n");
}

function lighthouseSection(scan: ScanResult): string {
  const lh = scan.lighthouse!;
  const fmt = (n: number | null) => (n == null ? "—" : String(n));
  return [
    `## Lighthouse scores`,
    ``,
    `| Performance | SEO | Accessibility | Best Practices |`,
    `| --- | --- | --- | --- |`,
    `| ${fmt(lh.performance)} | ${fmt(lh.seo)} | ${fmt(lh.accessibility)} | ${fmt(lh.bestPractices)} |`,
    ``,
  ].join("\n");
}
